### ISSUE TITLE
Error when trying to activate package in rmarkdown

### ISSUE THREAD

**Issue by FONDECYTACC** [Hemken/Statamarkdown#31] opened 2022-11-04 15:13 UTC
Get the following error when I try to activate the library in rmarkdown

```
Error in if (options$noisey == TRUE) message(paste("\n", options$engine, : argument is of length zero
```

**Comment by Hemken** [comment] 2022-11-04 15:28
Email me your document (it doesn’t look like I’ll need any data).

I’m away from the office and will be out for the next week, so expect some delay in my response.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

From: FONDECYTACC ***@***.***>
Sent: Friday, November 4, 2022 10:14 AM
To: Hemken/Statamarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/Statamarkdown] Error when trying to activate package in rmarkdown (Issue #31)


Get the following error when I try to activate the library in rmarkdown

Error in if (options$noisey == TRUE) message(paste("\n", options$engine, : argument is of length zero

**Comment by Hemken** [comment] 2022-11-04 15:53
Got it.  It’ll probably be a week before I can look in detail.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

**Comment by remlapmot** [comment] 2022-11-06 17:31
This is one of the most complicated Rmd files that I've ever seen.

Given that there's only 1 `stata` chunk right at the end of the file, could I ask, do you obtain this error in much simpler Rmd files?

**Comment by Hemken** [comment] 2023-02-04 14:16
I cannot reproduce this problem.

Other problems:
I cannot reproduce the error.

The YAML header is malformed, it has toc-float twice.

You load numerous packages that I have not installed (and shouldn't need to).  Please give us a simpler RMD file that produces the same error.

There is a code chunk that begins at line 73 and continues through the end of the document.

`knitr` checks that the beginning and ending code chunk fences (typically, backticks) must match in the number of backticks and the **amount of indentation**.  In this RMD file, the indendation does not match after line 73.

You should see a warning on the RStudio render tab similar to:
In addition: Warning messages:
1: The closing backticks on line 13 ("  ```") in stata-do.RMD do not match the opening backticks "```" on line 8. You are recommended to fix either the opening or closing delimiter of the code chunk to use exactly the same numbers of backticks and same level of indentation (or blockquote). 
2: The closing backticks on line 20 (" ```") in stata-do.RMD do not match the opening backticks "    ```" on line 15. You are recommended to fix either the opening or closing delimiter of the code chunk to use exactly the same numbers of backticks and same level of indentation (or blockquote).

**Comment by Hemken** [comment] 2023-02-04 14:17
If you would like to reopen this issue, please give us a much simpler example to reproduce the error message.

**Closed by Hemken** 2023-02-04 14:17 UTC
